sudo: false
language: rust
rust:
- stable
- nightly

before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo --only nightly doc

after_success:
  - travis-cargo --only nightly doc-upload
  - travis-cargo coveralls --no-sudo

addons:
  apt:
    packages:
      # Required for kcov
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

env:
  global:
  # override the default `--features unstable` used for the nightly branch (optional)
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: nP55f9O2fj7YPvRmu2bRl0Q6f6wXqZPMJbD1NBzHeBMRIz6+fcg/K96TnPIgys5kLBItJ93RtIDDy0IPJfIBpvDnOe6T262CKus9HgKJdwvkggcUGgpZ8InagiKqhvcq8n/vLjAooQs2hRTbUFGceFgx1kdgUP1wlhMQW8mYtg/KLL7/K2FQse7Yk31Co1ZKeW/ni4mLNVcKNA4mOtXINvsTl8LyXdMlwBRLczP/sJbBE5XRGAsVnvIJ8HS/A2DSGld4xwGJXHTNCfpu/tErcYu72gjGjoihaon1M5WvJHFkuzWuY2fs9aZ+jQ0TlCs0175ZL8D4F439htj7ByDeTRlEzZS30VZTB2UMnSxnx5EwVOeU/MB/5yE6kMMpnGmU5ILVRetVNqopODK8F0kOhkjVc2G5C1H2G14D7LaoWnMEjxOHgp5beswsCo4JbpsuEOSyz3oxqAZiKp6IJoVGnYJYR08fax2DSQLvYwen9ENFB+xEq/Gk3dYboLvNyrzX/oCraA7Y4iucd83YTxOhbSwP3r2IbgT39K+UfEAoqpbmDWpzfpliw2t36ETZax38FJ6Pnn+0gLwVcvTahY2klg+IUkkcojjZnigpUFFL3kkcjSk58cDjpwI/qX3ycfzbsvzD67G8c1U4xMDGLN+3mfwFsxQb0xrCjEP560v7JN4=

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: false