[package]
name = "fcm"
version = "0.1.4"
authors = ["Suvish Varghese Thoovamalayil <vishy1618@gmail.com>", "panicbit <panicbit.dev@gmail.com>"]
description = "An API to talk to GCM (Google Cloud Messaging) in Rust"
license = "MIT"
homepage = "https://github.com/panicbit/fcm-rust"
repository = "https://github.com/panicbit/fcm-rust"
#documentation = "http://vishy1618.github.io/gcm/gcm/"
keywords = ["fcm", "firebase", "gcm", "cloud", "messaging", "android", "ios"]

[dependencies]
rustc-serialize = "0.3.19"
hyper = "0.9.5"
