[package]
name = "fcm"
version = "0.1.1"
authors = ["Suvish Varghese Thoovamalayil <vishy1618@gmail.com>", "panicbit <panicbit.dev@gmail.com>"]
description = "An API to talk to FCM (Firebase Cloud Messaging) in Rust"
license = "MIT"
homepage = "https://github.com/panicbit/fcm-rust"
repository = "https://github.com/panicbit/fcm-rust"
documentation = "https://panicbit.github.io/fcm-rust/fcm/"
keywords = ["fcm", "firebase", "cloud", "messaging", "gcm"]

[dependencies]
rustc-serialize = "0.3.19"
hyper = "0.9.10"
retry-after = { git = "https://github.com/pimeys/retry-after" }
